name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
      - name: Lint & Format
        run: |
          ruff check
          ruff format --check
      - name: Tests
        run: pytest -q --cov soc_agent --cov-report=term-missing

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t soc-agent:ci .
